<?php
    $lang= array(
        "lang_fr" => "الفرنسية",
		"lang_ar" => "العربية"
    );
    $title= array(
        "titre" => "الأكاديمية الجهوية للنقل واللوجستيك",
        "Accompagnement" => "ISO مصاحبة شهادة",
        "salle" => "كراء القاعات",
        "article" => "الأخبار",
        "connexion" => "تسجيل الدخول"
    );
    $navbar= array(
        "Accueil"=>"الصفحة الرئيسية",
        "ARTLN"=>"أ.ج.ن.ل.ش",
        "Formations"=>"التكوينات",
        "Conseil"=>"استشارة ومرافقة",
        "Accompagnement"=>"ISO مرافقة الحصول على شهادة",
        "Categorisation"=>"OAS تصنيف مستويات الجمارك",
        "salles"=>"كراء القاعات",
        "Actualites"=>"الأخبار",
        "etudiant"=>"فضاء الطالب",
        "Contact"=>"تواصل معنا",
        "presentation"=>"تقديم الأكاديمية",
        "adresse"=>"شارع الحريري رقم 12 طنجة-المغرب",
        "espace"=>"فضاء الطالب",
        "deconnexion"=>"تسجيل خروج",
        "admin"=>"المسؤول",
        "dashboard"=>"لوحة القيادة"
    );
    $index= array(
        "banner_1" => "الأكاديمية الجهوية للنقل",
        "banner_2" => "واللوجستيك بجهة الشمال",
        "main_title" => "الأكاديمية الجهوية للنقل واللوجيستيك بجهة الشمال",
        "academie" => "الأكاديمية",
        "pourquoi" => "لماذا تخترتنا ؟",
        "qualite" => "جودة",
        "profes" => "احترافية",
        "carte" => "بطاقة مهنية",
        "plus" => "مزيد من المعلومات",
        "service" => "خدماتنا",
        "formation" => "السياقة الإيكولوجية",
        "certificat" => "ISO شهادة",
        "douane" => "تصنيف الجمارك",
        "location" => "كراء القاعات",
        "nosformation" => "التدريبات",
        "partenaires" => "شركائنا"
    );
    $ARTLN= array(
        "presentation" => "تقديم الأكاديمية",
        "directeur" => "كلمة المدير",
        "historique" => "تاريخ الأكاديمية",
        "notreAcademi" => "أكاديميتنا",
        "missions" => "مهمتنا",
        "objectifs" => "أهدافنا",
        "valeurs" => "قيمنا",
        "vision" => "رؤيتنا",
        "organigramme" => "المخطط التنظيمي للأكاديمية",
        "director" => "المدير",
        "assistante" => "مساعد المدير",
        "administration" => "إدارة",
        "department_a" => "قسم أ",
        "department_b" => "قسم ب",
        "department_c" => "قسم ج",
        "department_d" => "قسم د",
        "section_A1" => "القسم A1.",
        "section_A2" => "القسم A2.",
        "section_A3" => "القسم A3.",
        "section_B1" => "القسم B1.",
        "section_B2" => "القسم B2.",
        "section_B3" => "القسم B3.",
        "section_C1" => "القسم C1.",
        "section_C2" => "القسم C2.",
        "section_C3" => "القسم C3.",
        "section_D1" => "القسم D1.",
        "section_D2" => "القسم D2.",
        "section_D3" => "القسم D3.",
    );
    $forma= array(
        "presentation" => "عرض التكوين",
        "description" => "الوصف والهدف من هذا التكوين",
        "cursus" => "دورات تدريبية",
        "matieres" => "المواد",
        "durée" => "مدة / س.",
        "inscrivez" => "التسجل من هنا"
    );
    $accompagenemt= array(
        "accompagnement" => "ISO مصاحبة شهادة",
        "pourquoi" => "لماذا الشهادة",
        "categorisation" => "ISO التصنيف",
        "choisir" => "اختار",
        "accompa" => "مصاحبة",
        "choisir_modal" => "ISO اختيار مرافقة",
        "choisir_select" => "اختر المصاحبة الخاصة بك",
        "choisir_btn" => "اختر المصاحبة الخاصة بك",
        "fermer" => "اغلاق",
        "ISO" => "ISO"
    );
    $douane= array(
        "categorisation" => "تصنيف الوضع الجمركي",
        "status" => "الوضع الجمركي لماذا؟",
        "douane" => "تصنيف الجمارك",
        "slide_a" => "بعض محتوى العنصر النائب التمثيلي للشريحة الأولى",
        "slide_b" => "بعض محتوى العنصر النائب التمثيلي للانزلاق الثاني",
        "slide_c" => "بعض محتوى العنصر النائب التمثيلي للانزلاق الثالث",
        "choisir_select" => "اختر الفئة الخاصة بك",
    );
    $salle= array(
        "location" => "كراء قاعات التكوين",
        "dirhams" => "درهم",
        "personne" => "الأشخاص",
        "reservez" => "الحجز",
        "salle_nom" => "حجز",
        "description" => "وصف القاعة",
        "services" => "خدمات",
        "image" => "صور القاعة",
        "reservation" => "حجز",
        "nom" => "الاسم الكامل",
        "num" => "رقم الهاتف",
        "email" => "البريد الإلكتروني",
        "location_date" => "تاريخ الكراء",
        "date" => "تاريخ",
        "debut" => "وقت البدء",
        "fin" => "وقت النهاية",
        "verifier" => "تأكد من الوقت",
        "comment" => "اضافة تعليق"
    );
    $artic= array(
        "accueil" => "الرئيسية",
        "actualites" => "أخبار",
        "lire" => "اقرأ أيضا",
        "publie" => "نشرت",
        "Commentaire" => "التعليقات",
        "Commentaires" => "تعليقات",
        "laissez" => "اترك تعليقا",
        "prenom" => "اسمك",
        "nom" => "اسمك",
        "comment" => "اضافة تعليق",
        "Ecrire" => "اكتب تعليقك",
    );
    $login= array(
        "connexion" => "تسجيل الدخول",
        "CIN" => "بطاقة التعريف",
        "passe" => "كلمة المرور",
        "inscrire" => "التسجيل من هنا"
    );
    $footer= array(
        "contactez" => "اتصل بنا",
        "trouver" => "كيف تجدنا",
        "envoyermessage" => "أرسل رسالة",
        "nom" => "اسمك",
        "email" => "بريدك الإلكتروني",
        "sujet" => "الموضوع",
        "message" => "رسالتك",
        "btn_message" => "أرسل رسالتك",
        "liens" => "روابط مفيدة",
        "adresse_footer" => "عنوان المقر",
        "adresse"=>"شارع الحريري رقم 12",
        "ville" => "طنجة، المغرب",
        "propos" => " ARTLN حول",
        "phone" => "هاتف",
        "fix" => "هاتف ثابت",
        "fax" => "فاكس",
        "email_footer" => "بريد الالكتروني"
    );
?>
