<?php
    $lang= array(
        "lang_fr" => "Français",
		"lang_ar" => "Arabe"
    );
    $title= array(
        "titre" => "ARTL Nord",
        "Accompagnement" => "Accompagnement à la certification ISO",
        "Categoratsion" => "Catégoratsion de la douane",
        "salle" => "Location des salles",
        "article" => "Articles",
        "connexion" => "Connexion"
    );
    $navbar= array(
        "Accueil"=>"Accueil",
        "ARTLN"=>"ARTLN",
        "Formations"=>"Formations",
        "Conseil"=>"Conseil & Accompagnement",
        "Accompagnement"=>"Accompagnement à la certification  ISO",
        "Categorisation"=>"Catégorisation de la douane (OEA)",
        "salles"=>"Location des salles",
        "Actualites"=>"Actualités",
        "etudiant"=>"Espace étudiant",
        "Contact"=>"Contact",
        "presentation"=>"Présentation ARTL Nord",
        "adresse"=>"Boulevard Hariri N°12 Tanger-Maroc",
        "espace"=>"Espace étudiant",
        "deconnexion"=>"Déconnexion",
        "admin"=>"Admin",
        "dashboard"=>"Tableau de bord",
    );
    $index= array(
        "banner_1" => "Académie Régionale du Transport",
        "banner_2" => "et de Logistique du Nord",
        "main_title" => "Académie ARTL Nord",
        "academie" => "Académie",
        "pourquoi" => "Pourquoi nous choisir ?",
        "qualite" => "Qualité",
        "profes" => "Profissionalisme",
        "carte" => "Carte professionnelle",
        "plus" => "Plus d'information",
        "service" => "Nos Services",
        "formation" => "Formation éco-conduite",
        "certificat" => "Certification ISO",
        "douane" => "Catégorisation Douane",
        "location" => "Location des salles",
        "nosformation" => "Nos formations",
        "partenaires" => "Nos partenaires"
    );
    $ARTLN= array(
        "presentation" => "Présentation ARTL Nord",
        "directeur" => "Mot de directeur",
        "historique" => "Historique",
        "notreAcademi" => "Notre Académie",
        "missions" => "Nos missions",
        "objectifs" => "Nos objectifs",
        "valeurs" => "Nos valeurs",
        "vision" => "Notre vision",
        "organigramme" => "Organigramme de l'académie",
        "director" => "Director",
        "assistante" => "Assistante Director",
        "administration" => "Administration",
        "department_a" => "Department A",
        "department_b" => "Department B",
        "department_c" => "Department C",
        "department_d" => "Department D",
        "section_A1" => "Section A1",
        "section_A2" => "Section A2",
        "section_A3" => "Section A3",
        "section_B1" => "Section B1",
        "section_B2" => "Section B2",
        "section_B3" => "Section B3",
        "section_C1" => "Section C1",
        "section_C2" => "Section C2",
        "section_C3" => "Section C3",
        "section_D1" => "Section D1",
        "section_D2" => "Section D2",
        "section_D3" => "Section D3",
        "pres" => "Présentation de la formation",
        "description" => "Description et objectif de cette formation",
        "cursus" => "Cursus de la formation",
        "matieres" => "Matières",
        "durée" => "Durée/h",
        "inscrivez" => "Inscrivez-vous ici"
    );
    $forma= array(
        "presentation" => "Présentation de la formation",
        "description" => "Description et objectif de cette formation",
        "cursus" => "Cursus de la formation",
        "matieres" => "Matières",
        "durée" => "Durée/h",
        "inscrivez" => "Inscrivez-vous ici"
    );
    $accompagenemt= array(
        "accompagnement" => "Accompagnement à la certification ISO",
        "pourquoi" => "Pourquoi la certification",
        "categorisation" => "Catégorisation ISO",
        "choisir" => "Choisir",
        "accompa" => "Accompagnement",
        "choisir_modal" => "Choisir un Accompagnement ISO",
        "choisir_select" => "Choisir votre Accompagnement ISO",
        "choisir_btn" => "Choisir votre accompagnement",
        "fermer" => "Fermer",
        "ISO" => "ISO"
    );
    $douane= array(
        "categorisation" => "La Catégorisation au Statut de Douane",
        "status" => "Le status douane pourquoi ?",
        "douane" => "Catégorisation de la douane",
        "slide_a" => "Some representative placeholder content for the first slide",
        "slide_b" => "Some representative placeholder content for the second slide",
        "slide_c" => "Some representative placeholder content for the third slide",
        "choisir_select" => "Choisir votre Catégorie",
    );
    $salle= array(
        "location" => "Location des salles de formation",
        "dirhams" => "dhs/jour",
        "personne" => "Personnes",
        "reservez" => "Réservez",
        "salle_nom" => "Location de la",
        "description" => "Description de la salle",
        "services" => "Services",
        "image" => "Nos images",
        "reservation" => "Réservation de la",
        "nom" => "Nom complet",
        "num" => "Numéro de téléphone",
        "email" => "Adresse email",
        "location_date" => "Date de location",
        "date" => "Date",
        "debut" => "Heure de début",
        "fin" => "Heure de fin",
        "verifier" => "Vérifier dispnobilité",
        "comment" => "Votre Commentaire"
    );
    $artic= array(
        "accueil" => "Accueil",
        "actualites" => "Actualités",
        "lire" => "Lire aussi",
        "publie" => " Publiéle",
        "Commentaire" => "Les Commentaires",
        "Commentaires" => "Commentaires",
        "laissez" => "Laissez un commentaire",
        "prenom" => "Votre Prénom",
        "nom" => "Votre Nom",
        "comment" => "Votre Commentaire",
        "Ecrire" => "Ecrire votre commentaire",
    );
    $login= array(
        "connexion" => "Connexion",
        "CIN" => "CIN",
        "passe" => "Mot de passe",
        "inscrire" => "S'inscrire Ici"
    );
    $footer= array(
        "contactez" => "Contactez-nous",
        "trouver" => "Comment nous trouver",
        "envoyermessage" => "Envoyez-nous un message",
        "nom" => "Votre nom",
        "email" => "Votre email",
        "sujet" => "Sujet",
        "message" => "Votre message",
        "btn_message" => "Envoyer votre message",
        "liens" => "Liens utils",
        "adresse_footer" => "Adresse",
        "adresse" => "Boulevard Hariri N°12",
        "ville" => "Tanger-Maroc",
        "propos" => "A propos de nous",
        "phone" => "Téléphone",
        "fix" => "Fix",
        "fax" => "Fax",
        "email_footer" => "Email"
    );
?>